apiVersion: v1
kind: Config
clusters:
  - name: arn:aws:eks:us-east-1:981416785555:cluster/ex-eks-managed-node-group-c
    cluster:
      server: https://CFC44DB04084F45A0684D12CA5E8AD48.gr7.us-east-1.eks.amazonaws.com
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EWXdPVEV6TURRek4xb1hEVE16TURZd05qRXpNRFF6TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT2ZJCjBQQk05bmllcUtYb3FtcmE3YnI4RDhtYmtNTkVwM0VOckhxUTZJTUpZRU1oNlFFRFJIZys1RTQ0S3VoYVgrTHAKVDlOblJmVHZBQWV0RTRCU3cvNjVHV3BsZ2M5S1FRaEFCM2R2c20yNUhZbDRDaEpXeEdwQTQ1NmJxdXM5UkxmbwpLcHlwdjBPY0l6WXloaXVuSHE2OVpDV1l4ODZpQ0dON0hJZXduZldaTG9RYTJEVTRKaEhzRVZGZnZ5eFozb2hTCkZtQmV5QW5kbUp2dDIzQk9CdlNUdFBHdjB1SG00aEp6V0RmY1Q3YnF3aE1yL3dTcnlNRS8xZUtVZ09QZ2VrWkgKeW9HclR6by8xZEM4bEQwcHNKalNScGhOc3lITnQzNVNQekMrRzloM3Y3bGhtNGg3eUZoL1Y4RnpraVJQbEdvUwp0ZU9xeVlqSDhpb1J2NVUyWERVQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZBVVo0b0p2MlZnWHA0K29Zb21Vc044YzBFZW5NQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ3NpUm5xT1JDcDRZUUp3ZWpHNQpiR1VFT0lKdXlTZHNJWkxjTGlwdmthOExFZkNnR2ZMa0UralNxaTVzUkg5TTZwa1FYY25pcGdPRVRIQnJyTlpxCmlKL1RGNlFWUnM0ekZEMVNubVBWamlYWnBqOVNWdVhKaHoxMEU3UnI3L25UbUNMNTBxVHJtM0dFamg3K2JBUWcKSVc4Tmp1eEV1RGVvcENzLzV2SHdnN29QTUJ2QUpLVzlIa1M3eTlOS3FJU3Y3S0xua0ROTzBmZ0UxbU1jQzRCMwpjOUZBK0ROT0dnS0dYelhNbktGM2JLNU10RzBqaHNuNjIwMzRWcEFacTZiOFZPR3Q5SUFGdDRGMEt3K1pyL1pXCnJzbHVSN3dZRkZlMXZHQWlQSXg0Ry95TVNhYlRNMW5SaTEyRGhtNUdVNHdBeE5NYm9qbXJ4MUpuSXB6OEJNaXcKS09NPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      insecure-skip-tls-verify: false
users:
  - name: arn:aws:eks:us-east-1:981416785555:cluster/ex-eks-managed-node-group-c
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - '--region'
          - us-east-1
          - eks
          - get-token
          - '--cluster-name'
          - ex-eks-managed-node-group-c
          - '--output'
          - json
        command: aws
contexts: []
preferences: {}
current-context: arn:aws:eks:us-east-1:981416785555:cluster/ex-eks-managed-node-group-c
