trusted_account_number = "879500880845"
developer_role = "DeveloperAccessRoleDev"
devops_role = "DevopsAccessRoleDev"
developer_policy = "Read-permissions-on-EKS"
devops_policy = "Full-permissions"
stage = "dev"
