apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.saSecretRole }} 

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Values.serviceAccountName }}-role"
rules:
- apiGroups: [""] 
  resources: ["secrets"] 
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.serviceAccountName }}-rolebinding"
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ .Values.serviceAccountName }}-role"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}



