apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
   name: aws-secrets
   namespace: {{ .Values.namespace }}
spec:
  provider: aws
  secretObjects:
  - secretName: {{ .Values.secretName }}
    type: Opaque
    data:
      - objectName: dbusername
        key: username
      - objectName: dbpassword
        key:  password
  parameters:
    objects: |
      - objectName: "{{ .Values.secretName }}"
        objectType: "secretsmanager"
        jmesPath:
        - path: "username"
          objectAlias: "dbusername"
        - path: "password"
          objectAlias: "dbpassword"