apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: logging
spec:
  provider: aws
  secretObjects:
    - secretName: efk-secret-22
      type: Opaque
      data:
        - objectName: kusername
          key: username
        - objectName: kpassword
          key: password
  parameters:
    objects: |
      - objectName: "efk-secret-22"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: kusername
          - path: password
            objectAlias: kpassword
