apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.applicationName }}-svc"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.applicationName }}
spec:
  selector:
    app: {{ .Values.applicationName }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP