---

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: monitoring
spec:
  provider: aws
  secretObjects:
  - secretName: grafana-secret
    type: Opaque
    data:
    - objectName: gusername
      key: username
    - objectName: gpassword
      key: password
  parameters:
    objects: |
      - objectName: "MySecret"
        objectType: "secretsmanager"
        jmesPath: 
        - path: "username"
          objectAlias: "gusername"
        - path: "password"
          objectAlias: "gpassword"
